//
// Created by Sriram Srinivasa Kalki on 12/30/21.
//

#ifndef USACO_CPP__LUNARNEWYEARANDNUMBERDIVISION_H
#define USACO_CPP__LUNARNEWYEARANDNUMBERDIVISION_H


class LunarNewYearAndNumberDivision {

};


#endif //USACO_CPP__LUNARNEWYEARANDNUMBERDIVISION_H
